#!groovy

def setGitHubBuildStatus(String status, String message, String context) {
    script {
        withCredentials([string(credentialsId: 'GitHub_API_Token',
                variable: 'api_token')]) {
            sh """
                curl -H "Authorization: token ${api_token}" \
                --request POST \
                --data '{ \
                    "state": "${status}", \
                    "description": "${message} on ${context}", \
                    "target_url": "$BUILD_URL", \
                    "context": "jenkins/${context}" \
                }' \
                ${env.GIT_URL}/statuses/${env.GIT_COMMIT}
            """
        }
    }
}

def getGitCommitAuthorEmail() {
    withCredentials([string(credentialsId: 'GitHub_API_Token',
            variable: 'api_token')]) {
        return sh(
            script: """
                commit_url="\$(\\
                    curl -s -H "Authorization: token ${api_token}" \\
                    --request GET ${env.GIT_URL}/git/ref/heads/${env.JOB_BASE_NAME} \\
                    | jq ".object.url" | tr -d '"'\\
                )" &&
                echo "\$(\\
                    curl -s -H "Authorization: token ${api_token}" \\
                    --request GET \$commit_url |  jq '.author.email' | tr -d '"'\\
                )"
            """,
            returnStdout: true
        )
    }
}

pipeline {

    agent { label env.AGENT }

    triggers {
        GenericTrigger(
             genericVariables: [
                [key: 'ref', value: '$.ref']
             ],

             causeString: 'Triggered on $ref',

             token: 'GitHub_API_Token',

             printContributedVariables: true,
             printPostContent: true,

             silentResponse: false,

             regexpFilterText: '$ref',
             regexpFilterExpression: 'refs/head/' + env.JOB_BASE_NAME
        )
        pollSCM('')
    }

    stages {

        stage("Notify") {
            steps {
                setGitHubBuildStatus("pending", "Starting", "Linux")
                echo "Branch: ${env.JOB_BASE_NAME}"
            }
        }

        stage("Set up") {
            steps {
                script {
                    if (isUnix()) {
                        sh """
                            module load conda/3 &&
                            module load gcc &&
                            export CC=gcc
                            conda config --append channels free &&
                            conda create --name py python=3.6.0 -y &&
                            conda activate py &&
                            python -m pip install --upgrade --user pip &&
                            python -m pip install numpy &&
                            python -m pip install euphonic[phonopy_reader]
                        """
                    }
                }
            }
        }

        stage("Test") {
            steps {
                sh """
                    module load matlab/\$MATLAB_VERSION &&
                    module load conda/3 &&
                    cd test &&
                    matlab -nosplash - nodesktop -wait -batch "run('run_tests.m')"
                """
            }
        }
    }

    post {

        success {
	    script {
                if (env.AGENT == 'sl7') {
                    script {
                        setGitHubBuildStatus("success", "Successful", "Linux")
                    }
                }
	    }
        }

        unsuccessful {
	    script {
                if (env.AGENT == 'sl7') {
                    script {
                        setGitHubBuildStatus("failure", "Unsuccessful", "Linux")
                        def email = getGitCommitAuthorEmail()
                        mail (
                            to: "$email",
                            subject: "Linux failed pipeline: ${env.JOB_BASE_NAME}",
                            body: "See ${env.BUILD_URL}"
                        )
                    }
                }
	    }
        }

        cleanup {
            deleteDir()
        }

    }
}
